[package]
name = "nanoserde-size"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanoserde = { version = "0.2", default-features = false, features = ["json"] }

[profile.release]
strip = true
