[package]
name = "pico-args-size"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = { version = "0.5.0", features = ["combined-flags", "eq-separator"] }

[profile.release]
strip = true
